"""Description of the changes

Revision ID: 01f0d35ce84d
Revises: 
Create Date: 2025-05-10 21:38:49.711946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01f0d35ce84d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_ID', sa.String(length=20), nullable=True))
        batch_op.create_unique_constraint(None, ['user_ID'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('user_ID')

    # ### end Alembic commands ###
